version: '3.7'

services:
  svc_nginx:
    image: choggarth/nginx:1.14.0
    container_name: svc_nginx
    restart: always
    command: dockerize
      -timeout 600s
      -wait tcp://svc_elastic:9200
      -wait tcp://svc_kibana:5601
      -wait tcp://app_greyhound:3000
      -template /work/nginx/conf.d/http.conf:/etc/nginx/conf.d/_http.conf
      -template /work/nginx/conf.d/watchdog.conf:/etc/nginx/conf.d/watchdog.conf
      nginx -g 'daemon off;'
    environment:
      - ROOT_HOST=${ROOT_HOST}
    ports:
      - 80:80
      - 443:443
    depends_on: 
      - svc_elastic
      - svc_kibana
      - app_greyhound
    volumes:
      - ../services/nginx/conf:/work/nginx
      - ../services/nginx/conf/conf.d/shared:/etc/nginx/conf.d/shared
    # logging: 
    #   driver: none

  svc_elastic:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.4.0
    container_name: svc_elastic
    restart: always
    environment:
      - xpack.security.enabled=false
      - discovery.type=single-node
    ulimits:
      memlock:
        soft: -1
        hard: -1
      nofile:
        soft: 65536
        hard: 65536
    cap_add: 
      - IPC_LOCK
    volumes:
      - elasticsearch-data-volume:/usr/share/elasticsearch/data
    ports:
      - 9200:9200

  svc_kibana:
    container_name: svc_kibana
    image: docker.elastic.co/kibana/kibana:7.4.0
    restart: always
    environment: 
      - ELASTICSEARCH_HOSTS=http://svc_elastic:9200
    ports:
      - 5601:5601
    depends_on: 
      - svc_elastic

  app_greyhound:
    container_name: app_greyhound
    image: chrisgarrett/node-dev:12.4.0
    command: dockerize -wait tcp://svc_kibana:5601 -timeout 300s npm run start
    user: ${LOCAL_USER_ID}:${LOCAL_USER_GROUP_ID}
    volumes:
      - ../sources/js/apps/greyhound/src:/work/app
    depends_on:
      - svc_kibana

volumes:
  elasticsearch-data-volume:
    driver: local